const colors = {
  light: {
    text: "#1C1C1E",
    tint: "#4F46E5",
    background: "#FAFAF9",
    foreground: "#1C1C1E",
    card: "#FFFFFF",
    cardForeground: "#1C1C1E",
    primary: "#4F46E5",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF2FF",
    secondaryForeground: "#4F46E5",
    muted: "#F3F4F6",
    mutedForeground: "#6B7280",
    accent: "#EEF2FF",
    accentForeground: "#4F46E5",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E7EB",
    input: "#E5E7EB",
  },
  dark: {
    text: "#F9FAFB",
    tint: "#818CF8",
    background: "#0F0F10",
    foreground: "#F9FAFB",
    card: "#1C1C1E",
    cardForeground: "#F9FAFB",
    primary: "#6366F1",
    primaryForeground: "#FFFFFF",
    secondary: "#1E1E2E",
    secondaryForeground: "#818CF8",
    muted: "#1C1C1E",
    mutedForeground: "#6B7280",
    accent: "#1E1E2E",
    accentForeground: "#818CF8",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2D",
    input: "#2A2A2D",
  },
  radius: 14,
};

export default colors;
